### ISSUE TITLE
What is the differences between NamespacedEnums.jl and SuperEnum.jl?

### ISSUE THREAD

**Issue by singularitti** [christopher-dG/NamespacedEnums.jl#2]
Is it intentionally made different from https://github.com/kindlychung/SuperEnum.jl?

**Comment by christopher-dG** [comment]
Well, I didn't know that that package existed 🙃. If I had, I very likely wouldn't have written this one... It seems that there are slight differences in API but they do generally the same thing. I'll think about whether I actually want this to be registered over the next day or two.
Thanks for bringing it up!

**Comment by christopher-dG** [comment]
Ok after using SuperEnum for 2 minutes, I have come to the conclusion that this package is just a worse version of it. Use SuperEnum instead! I have closed my registration PR.
